### ISSUE TITLE
question about some number mentioned in paper

### ISSUE THREAD

**Issue by lai-pf** [DylanAuty/ObjCAViT#2]
![image](https://user-images.githubusercontent.com/32856760/216868105-759c2682-45d1-4d35-b93c-82cef3d31d49.png)
the result rms of baseline Adabins in your paper is 0.428
but the origin Adabins can get better score, in Adabins' paper, this rms should be 0.36
Can you tell me the difference between origin Adabins and your Adabins reimpl
Thanks for your help and this can help me a lot.

**Comment by DylanAuty** [comment]
Hi, thank you for your question. The main difference is the batch size: the original AdaBins is trained with a batch size of 16, but due to hardware limitations we were only able to use a batch size of 8 on our experiments, so we needed to provide a baseline with a similar batch size for a fair comparison. Our experiments use the original AdaBins dataloader from the [original AdaBins repository](https://github.com/shariqfarooq123/AdaBins) (with very minor modifications), which includes also the data augmentation. Much of the code for the reimplemented AdaBins is also sourced directly from the AdaBins repository. We also use the same optimizer and optimizer settings as AdaBins.

We implemented our own training loop for use with our experiments, and "AdaBins-Reimpl." is trained using this training loop. This was done to provide a fair comparison baseline to better show improvements with a minimum of unrelated variables (e.g. slight differences in implementations).
